ConfigVersion: 1
#(cht) 請不要更改上述設置，否則插件可能會無法運行
#(en) Please do not change the above settings, otherwise the plugin may not work
ServerName: ExpTech Server
ServerUUID: null
APIKey: =MQbXwsr=VvBX1K2dZNswvSF4dNDlz
#(cht) 放入 API Key (ExpTech)
#(en) Put in API Key (ExpTech)
BetaVersion: false
#(cht) Beta版本可能會出現錯誤或不穩定，適合喜歡嚐鮮的用戶升級體驗
#(en) Beta version may cause errors or instability, suitable for users who like early adopters to upgrade the experience
LogLevel: INFO
# INFO / DEBUG / TRACE

# ExpTech_Core